# Generated by Django 6.0.6 on 2026-07-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=20)),
                ('parked_hours', models.TimeField()),
                ('paid_amount', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
